version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    executor:
      name: python/default
    steps:
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            python3 --version
            poetry build
          name: build

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
          matrix:
            parameters:
              version:
                - "3.6"
                - "3.7"
                - "3.8"
      - build:
          requires:
            - python/test
