version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-packages:
          pkg-manager: poetry
      - python/save-cache
      - run:
          command: |
            poetry run pytest --version
          name: Test

workflows:
  main:
    jobs:
      - build
