version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  build-and-publish:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            python3 --version
          name: shrug
      - run:
          command: |
            poetry build
          name: build
      - run:
          command: |
            poetry config pypi-token.pypi $PYPI_TOKEN
            poetry publish
          name: publish

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
          matrix:
            parameters:
              version:
                - "3.6"
                - "3.7"
                - "3.8"
      - build-and-publish:
          requires:
            - python/test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
