version: 2.1

orbs:
  docker: circleci/docker@2.0.2
  python: circleci/python@2.0.1

jobs:
  build-package:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            poetry build
          name: build
      - persist_to_workspace:
          root: .
          paths:
            - dist
            - pyproject.toml
  publish-package:
    executor:
      name: python/default
    steps:
      - attach_workspace:
          at: .
      - run:
          command: |
            poetry config pypi-token.pypi $PYPI_TOKEN
            poetry publish
          name: publish
  build-container:
    executor: docker/machine
    steps:
      - checkout
      - docker/build:
          image: darksoy/$CIRCLE_PROJECT_REPONAME
          extra_build_args: --progress plain
    environment:
      DOCKER_BUILDKIT: 1
  version-check:
    executor:
      name: python/default
    steps:
      - checkout
      - run:
        # https://stackoverflow.com/a/31933234
          command: |
            curl -sSf -o 1.json https://python-api.soy.se/v1/versions
            awk '/version: \[/ { print $2 }' .circleci/config.yml > 2.json
            jq --exit-status --argfile a 1.json --argfile b 2.json -n '($a | (.. | arrays) |= sort) as $a | ($b | (.. | arrays) |= sort) as $b | $a == $b'

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
          filters:
            tags:
              only: /.+/
          matrix:
            parameters:
              version: ["3.7","3.8","3.9","3.10","3.11"]
      - build-package:
          requires:
            - python/test
          filters:
            tags:
              only: /.+/
      - publish-package:
          requires:
            -  build-package
          filters:
            tags:
              only: /.+/
            branches:
              ignore: /.*/
      - build-container:
          requires:
            -  python/test
          filters:
            tags:
              only: /.+/
      - docker/publish:
          requires:
            - build-container
          context:
            - docker-hub-credentials
          filters:
            tags:
              only: /.+/
            branches:
              ignore: /.*/
          image: darksoy/$CIRCLE_PROJECT_REPONAME
          tag: "latest,$CIRCLE_TAG"
  version-check:
    triggers:
      - schedule:
          cron: "3 2 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - version-check
