version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  test:
    parameters:
      version:
        description: "The Python environment version to be tested."
        default: "3.6"
        type: string
    executor:
      name: python/default
      tag: <<parameters.version>>
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            python3 --version
            poetry run pytest
          name: Test

workflows:
  main:
    jobs:
      - test:
          matrix:
            parameters:
              version:
                - "3.6"
                - "3.7"
                - "3.8"
