version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            python3 --version
            poetry run pytest
          name: Test

workflows:
  main:
    jobs:
      - test:
          name: test-v<< matrix.tag >>
          matrix:
            parameters:
              tag: ["3.5", "3.6", "3.7", "3.8", "3.9"]
