version: 2.1

orbs:
  docker: circleci/docker@1.5.0
  python: circleci/python@1.3.2

jobs:
  build-and-publish:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            python3 --version
          name: shrug
      - run:
          command: |
            poetry build
          name: build
      - run:
          command: |
            poetry config pypi-token.pypi $PYPI_TOKEN
            poetry publish
          name: publish
  version-check:
    executor:
      name: python/default
    steps:
      - checkout
      # https://sources.debian.org/api/src/python3-defaults/
      - run:
          command: |
            jq --version
            curl --version

workflows:
  main:
    jobs:
      - python/test:
          pkg-manager: poetry
          test-tool: pytest
          matrix:
            parameters:
              version:
                - "3.6"
                - "3.7"
                - "3.8"
                - "3.9"
      - build-and-publish:
          requires:
            - python/test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - docker/publish:
          requires:
            - build-and-publish
          image: darksoy/$CIRCLE_PROJECT_REPONAME
  version-check:
    triggers:
      - schedule:
          cron: "3 2 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - version-check
