version: 2.1

orbs:
  python: circleci/python@1.3.2

jobs:
  test:
    executor:
      name: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: poetry
      - run:
          command: |
            python --version
            python3 --version
            poetry run pytest
          name: Test

workflows:
  main:
    jobs:
      - test:
        - tag: "3.7"
